default_language_version:
    python: python3.11

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
          - id: trailing-whitespace

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
          - id: black-jupyter

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args:
                - --settings-path=.isort.cfg

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.0.0-alpha.6"
      hooks:
          - id: prettier
